name: Create Release on push (if ISO files changed)
on:
  push:
    branches:
      - main  # Triggered whenever something is pushed on main (force or no force)
    paths:
      - 'regions/**/*.json'

permissions:
  contents: write
  packages: write

jobs:
  create-release:
    if: success()
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        # Most recent Python version as of 2024-12-29.
        with:
          python-version: '3.13'
      # Code does not have dependencies. Otherwise, would need a step here to `pip install` stuff.
      - name: Execute merge parsing script.
        run: python .scripts/parse_release.py
      - name: set date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      - name: set short commit SHA
        run: echo "COMMIT_SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      - name: Output proposed tag.
        run: echo "${{ env.date }}-${{ env.COMMIT_SHORT_SHA }}"
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "${{ env.date }}-${{ env.COMMIT_SHORT_SHA }}"
          name: Release ${{ env.date }}, commit ${{ env.COMMIT_SHORT_SHA }}
          files: iso_3166_data.json
          token: ${{ secrets.GITHUB_TOKEN }}
